{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a92b5fa8-07dc-4304-ac92-f6eab4d4132b",
   "metadata": {},
   "outputs": [],
   "source": [
    "### I've added some dask operations and functionality on top of what the \n",
    "### original tutorial had but it's mostly Hamed's code from Raster Processing class 15"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c8a5049c-6c1e-4d15-96a3-5e42950c0501",
   "metadata": {},
   "outputs": [],
   "source": [
    "import xarray as xr\n",
    "import rioxarray as rxr\n",
    "from rioxarray.merge import merge_datasets\n",
    "import numpy as np\n",
    "import dask\n",
    "import pyproj\n",
    "from rasterio.enums import Resampling\n",
    "from shapely.geometry import box, mapping\n",
    "from dask.distributed import Client\n",
    "from dask import delayed\n",
    "\n",
    "import os\n",
    "import requests\n",
    "from tqdm import tqdm\n",
    "import dask.array as da\n",
    "\n",
    "import pystac_client\n",
    "import planetary_computer\n",
    "from dask.diagnostics import ProgressBar  # Useful for monitoring progress\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "0a4d56ea-3f61-42ce-a70d-0a9d42d5aab3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/root/miniconda3/lib/python3.12/site-packages/distributed/node.py:187: UserWarning: Port 8787 is already in use.\n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the HTTP server on port 35759 instead\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "http://127.0.0.1:35759/status\n"
     ]
    }
   ],
   "source": [
    "from dask.distributed import Client\n",
    "\n",
    "# Start the Dask client\n",
    "client = Client(memory_limit='8GB')  # Adjust the memory limit based on your system's capacity\n",
    "\n",
    "# Print the dashboard link\n",
    "print(client.dashboard_link)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "4c7794e2-4cf1-4629-88d2-1e7896dd654f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def retrieve_stac_items_bbox(url, collection, bbox, datetime, max_items=10, pc_flag=False, max_cloud_cover=2): \n",
    "    \"\"\"\n",
    "    This function retrieves the latest STAC items from a STAC API, filtered by cloud cover.\n",
    "    \n",
    "    Parameters\n",
    "    ----------\n",
    "    url : str\n",
    "        The STAC API URL\n",
    "    collection : str\n",
    "        Collection ID to search in the STAC API\n",
    "    bbox : list or tuple\n",
    "        A tuple or list with coordinates of the target area for API search in the format (min x, min y, max x, max y)\n",
    "    datetime : str\n",
    "        ISO-8601 formatted date range, e.g., \"2020-01-01/2020-12-31\".\n",
    "    pc_flag : boolean\n",
    "        A boolean flag to specify whether the STAC API is Microsoft's planetary computer API. Default is set to False.\n",
    "    max_items : integer\n",
    "        Maximum number of items to retrieve from the STAC API. Default is 10.\n",
    "    max_cloud_cover : float\n",
    "        Maximum allowed cloud cover percentage for filtering. Default is 2%.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    items : Generator\n",
    "        The STAC item collection matching the query parameters.\n",
    "    \"\"\"\n",
    "    if pc_flag:\n",
    "        modifier = planetary_computer.sign_inplace\n",
    "    else:\n",
    "        modifier = None\n",
    "        \n",
    "    catalog = pystac_client.Client.open(\n",
    "        url=url,\n",
    "        modifier=modifier,\n",
    "    )\n",
    "\n",
    "    # Query for items, including the cloud cover filter\n",
    "    search_results = catalog.search(\n",
    "        collections=[collection],\n",
    "        bbox=bbox,\n",
    "        datetime=datetime,  # ISO-8601 formatted date range\n",
    "        query={\"eo:cloud_cover\": {\"lt\": max_cloud_cover}},  # Cloud cover filter\n",
    "        sortby=[\"-properties.datetime\"],\n",
    "        max_items=max_items\n",
    "    )\n",
    "    items = search_results.item_collection()\n",
    "\n",
    "    return items"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "201d1c81-5f91-427b-9b10-e9de18b6f93e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define parameters for Charlottesville, Virginia (1-degree square around the city center)\n",
    "url = \"https://planetarycomputer.microsoft.com/api/stac/v1\"\n",
    "collection = \"landsat-c2-l2\"\n",
    "\n",
    "bbox = [-79.5, 37.9, -78.5, 38.9]  # 1-degree square bounding box around Charlottesville\n",
    "bbox_geometry = mapping(box(*bbox))\n",
    "time_range = \"2020-01-01/2020-12-31\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "e18720f3-5f36-4d04-8c62-935b6137f0f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Query Landsat images for the bounding box and time range\n",
    "items = retrieve_stac_items_bbox(\n",
    "    url=url,\n",
    "    collection=collection,\n",
    "    bbox=bbox,\n",
    "    datetime=time_range,  # Pass the time range directly\n",
    "    max_items=1000,  # Retrieve up to 10 images\n",
    "    pc_flag=True  # Use Planetary Computer API\n",
    ")\n",
    "\n",
    "# # Print the retrieved items\n",
    "# for item in items:\n",
    "#     print(item.id, item.properties[\"datetime\"])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "fa424d78-443f-4206-ad4f-d339cfa64fbe",
   "metadata": {},
   "outputs": [],
   "source": [
    "def gen_stac_asset_urls(items, asset):\n",
    "    \"\"\"\n",
    "    This function receives an items collection returned by a STAC API, and returns\n",
    "    the urls of the requested `asset` in a list. \n",
    "\n",
    "    Inputs:\n",
    "        items : json collection\n",
    "            A STAC items collection returned by STAC API\n",
    "        asset : string\n",
    "            Name of an asset present in the `items` collection\n",
    "\n",
    "    Returns:\n",
    "        urls : list\n",
    "            List of all usls related to the `asset`\n",
    "            \n",
    "    \"\"\"\n",
    "\n",
    "    urls = []\n",
    "    for item in items:\n",
    "        urls.append(item.assets[asset].href)\n",
    "    \n",
    "    return urls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "29afe96a-7f98-458c-a58e-e3f8fce6cc74",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Example of loading red, green, and blue band URLs using Dask\n",
    "red_urls = gen_stac_asset_urls(items, \"red\")\n",
    "green_urls = gen_stac_asset_urls(items, \"green\")\n",
    "blue_urls = gen_stac_asset_urls(items, \"blue\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "ddff5275-fa1f-4b65-824c-d1d24eea62eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def open_rasters_with_dask(urls):\n",
    "    return [rxr.open_rasterio(url, lock=False, chunks={'x': 512, 'y': 512}).to_dataset(name=url.split('/')[-1]) for url in urls]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "00e67d37-e588-4b32-8554-f454e561c423",
   "metadata": {},
   "outputs": [],
   "source": [
    "with ProgressBar():\n",
    "    red_datasets = open_rasters_with_dask(red_urls)\n",
    "    green_datasets = open_rasters_with_dask(green_urls)\n",
    "    blue_datasets = open_rasters_with_dask(blue_urls)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "5fb755e2-478c-438b-803f-783a6c623f76",
   "metadata": {},
   "outputs": [],
   "source": [
    "def merge_in_batches(datasets, batch_size=5):\n",
    "    merged_result = None\n",
    "    for i in range(0, len(datasets), batch_size):\n",
    "        batch = datasets[i:i + batch_size]\n",
    "        batch_merged = xr.merge(batch)  # Merge the current batch\n",
    "        if merged_result is None:\n",
    "            merged_result = batch_merged\n",
    "        else:\n",
    "            merged_result = xr.merge([merged_result, batch_merged])  # Merge with previous result\n",
    "    return merged_result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "c6b7da94-77e3-427d-8e69-b3a95ac574d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "def dask_merge_datasets(datasets):\n",
    "    # Use delayed to merge datasets in batches\n",
    "    delayed_batches = merge_in_batches(datasets)\n",
    "    \n",
    "    # Convert merged dataset to Dask array\n",
    "    # We chunk the merged dataset after the delayed operations\n",
    "    dask_array = delayed_batches.chunk({'x': 2048, 'y': 2048})  # Ensure chunking is efficient\n",
    "    \n",
    "    # Compute the result in parallel once all tasks are delayed\n",
    "    result = dask.compute(dask_array)\n",
    "    return result[0]  # Return the first element, which is the result of the delayed computation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "40e3eca0-036c-4372-a05f-0687cc7be476",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 25\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 25\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 25\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 25\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 28\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 28\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 28\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 28\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 28\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 28\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 26\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 27\n",
      "  result = blockwise(\n",
      "/root/miniconda3/lib/python3.12/site-packages/dask/array/core.py:5028: PerformanceWarning: Increasing number of chunks by factor of 28\n",
      "  result = blockwise(\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54155' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63566' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54537' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63940' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54916' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64320' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62079' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64702' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53431' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62834' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53809' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63216' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63599' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61351' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63976' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61726' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "/root/miniconda3/lib/python3.12/site-packages/distributed/client.py:3371: UserWarning: Sending large graph of size 11.55 MiB.\n",
      "This may cause some slowdown.\n",
      "Consider loading the data with Dask directly\n",
      " or using futures or delayed objects to embed the data into the graph without repetition.\n",
      "See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.\n",
      "  warnings.warn(\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59486' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62110' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62493' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62871' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60621' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58380' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61006' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58760' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61386' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59139' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61762' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59516' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59899' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57653' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60280' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58028' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58409' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56170' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58792' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56543' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56922' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54688' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57304' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55064' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58065' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55819' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56200' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56579' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54333' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56958' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54716' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64128' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55097' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55474' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53227' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53611' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63020' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63399' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63775' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64159' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61912' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62290' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53263' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60428' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60808' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63435' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58941' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61564' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59322' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61946' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62326' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60077' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57837' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60459' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58213' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60841' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58588' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61220' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56728' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59354' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57107' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57482' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60113' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57865' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55626' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58246' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56001' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58624' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56375' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54138' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56759' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54518' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57141' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54898' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57519' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55273' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64687' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55656' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53412' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56036' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54169' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63584' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54552' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63957' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54933' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64335' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62094' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64716' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62475' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53447' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62853' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53826' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63230' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60989' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63614' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61367' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63993' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61744' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64372' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62124' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59884' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62508' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60261' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62888' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60636' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63266' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61020' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58774' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61401' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59156' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61779' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59530' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57287' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59914' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57667' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60296' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60673' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56185' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58807' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59190' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56938' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59566' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57318' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55080' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57701' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55457' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58082' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55834' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53594' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56214' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53975' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56595' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54352' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56975' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54730' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64144' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55112' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64521' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55491' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53243' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53625' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63038' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54006' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63416' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54387' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63790' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54766' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64173' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61930' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64553' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62307' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53280' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62684' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60442' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63068' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60822' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61200' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63827' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61578' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59339' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61961' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59715' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62343' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60473' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58231' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60856' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58606' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58985' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59368' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57123' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59750' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57879' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55639' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58261' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56017' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58641' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56391' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59022' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54536' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57155' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54914' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57536' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55290' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57915' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55670' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53429' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56051' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-56428' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54183' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63597' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54567' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63973' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54949' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-55325' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64730' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53462' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62868' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-53843' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63246' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-54219' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63628' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61385' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-64008' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61759' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62139' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59898' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62522' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60277' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-62904' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60654' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-63283' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61034' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58789' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61416' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59170' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61796' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-59546' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-57685' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60310' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58062' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-60690' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-58440' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-61070' coro=<Client._gather.<locals>.wait() done, defined at /root/miniconda3/lib/python3.12/site-packages/distributed/client.py:2395> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/lib/python3.12/site-packages/distributed/client.py\", line 2404, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    }
   ],
   "source": [
    "# Mosaicking process with Dask\n",
    "with ProgressBar():\n",
    "    mosaic_red = dask_merge_datasets(red_datasets)\n",
    "    mosaic_blue = dask_merge_datasets(blue_datasets)\n",
    "    mosaic_green = dask_merge_datasets(green_datasets)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5298e1a-c06b-4706-81ad-57b884ea3210",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Clip function for Dask\n",
    "def dask_clip(dask_array, bbox_geometry, crs=4326):\n",
    "    \"\"\"\n",
    "    Clip a Dask array lazily to a given bounding box using RioClip.\n",
    "    \n",
    "    Parameters\n",
    "    ----------\n",
    "    dask_array : xarray.DataArray or dask.array\n",
    "        The Dask array to be clipped.\n",
    "    bbox_geometry : dict\n",
    "        The geometry for clipping (GeoJSON format).\n",
    "    crs : int, optional\n",
    "        The coordinate reference system (CRS) for the bounding box, default is 4326.\n",
    "        \n",
    "    Returns\n",
    "    -------\n",
    "    clipped : xarray.DataArray\n",
    "        The clipped Dask array.\n",
    "    \"\"\"\n",
    "    return dask_array.rio.clip([bbox_geometry], crs=crs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d6a0b57f-dcc0-42c3-a69e-daeba8ffa87d",
   "metadata": {},
   "outputs": [],
   "source": [
    "with ProgressBar():\n",
    "    mosaic_red = dask_clip(mosaic_red, bbox_geometry)\n",
    "    mosaic_blue = dask_clip(mosaic_blue, bbox_geometry)\n",
    "    mosaic_green = dask_clip(mosaic_green, bbox_geometry)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a16d5288-30e0-4fad-a2a6-ce1149e49cc9",
   "metadata": {},
   "outputs": [],
   "source": [
    "with ProgressBar():\n",
    "    mosaic_red.red.rio.to_raster(\"red_clipped.tif\")\n",
    "    mosaic_blue.blue.rio.to_raster(\"blue_clipped.tif\")\n",
    "    mosaic_green.green.rio.to_raster(\"green_clipped.tif\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ccd1b306-a8cd-433f-88fd-460b9b98a990",
   "metadata": {},
   "outputs": [],
   "source": [
    "# mosaic_red.red.rio.to_raster(\"red_clipped.tif\")\n",
    "# mosaic_blue.red.rio.to_raster(\"blue_clipped.tif\")\n",
    "# mosaic_green.red.rio.to_raster(\"green_clipped.tif\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc488b25-d2ad-4634-bd69-2e8e5a8f16d9",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_mosaic = xr.merge([mosaic_red, mosaic_green, mosaic_blue])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1531e34d-3119-49ef-91ca-eb2575ac1015",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_mosaic.rio.to_raster('final_mosaic.tif')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4ae573e1-cb6e-4284-aff3-b9b7d76326a2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
